apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-readonly
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - events
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
# Constraint only to insighthub namespace
kind: RoleBinding 
metadata:
  name: mcp-readonly
  namespace: insighthub
subjects:
  - kind: ServiceAccount
    name: mcp-readonly
    namespace: insighthub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-readonly