apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insighthub-staging
  namespace: insighthub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: insighthub-efs-static
  volumeName: insighthub-staging-efs
