apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: insighthub
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_INSHIGHTHUB_SECRETS_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingestion-worker
  namespace: insighthub
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_INSHIGHTHUB_SECRETS_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-bootstrap
  namespace: insighthub
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_INSHIGHTHUB_SECRETS_ROLE_ARN
