apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: insighthub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: REPLACE_WITH_IMMUTABLE_WEB_ECR_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: API_INTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: insighthub-runtime
                  key: API_INTERNAL_URL
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: insighthub
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 3000
      targetPort: http
